#!/bin/sh

export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/bin:$PATH
export PATH=$HOME/.scripts/:$PATH
# export PATH=$HOME/.local/share/neovim/bin:$PATH
export PATH=$HOME:/home/bryant/.local/share/bob/nvim-bin:$PATH
export PATH=$HOME:/home/bryant/.spicetify:$PATH
export PATH=$HOME:~/.local/share/nvim/mason/bin:$PATH
export GPG_TTY=$(tty)
export PATH=~/.npm-global/bin:$PATH
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOPATH/bin:/usr/local/go/bin

# export FZF_DEFAULT_OPTS=" \
# --color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 \
# --color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
# --color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8"
