# Prompt: param 2 └─
[character]
success_symbol = " [╰─λ](bold #b4f9f8)"
error_symbol = " [](bold #e57474)"

# Third param
[directory]
format = "[$path]($style)[$lock_symbol]($lock_style) "
style = "fg:#67b0e8"
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "../"

[git_branch]
format = "[ ](fg:#FFFFFF)[$symbol$branch ]($style)"
symbol = " "
style = "bold #c47fd5"

[git_status]
format ='([\[$all_status$ahead_behind\] ]($style))'
conflicted = "="
ahead =	"[  $count ](fg:#8ccf7e)"
behind = "[  $count ](fg:#e57474)"
diverged = "⇕ ${ahead_count} ${behind_count}"
untracked = "[ ?$count ](fg:#6cbfbf)"
modified = "[ $count ](fg:#8ccf7e)"
staged = "[ $count ](fg:#6cbfbf)"
renamed = "[ »$count ](fg:#c47fd5)"
deleted = "[ ✘$count ](fg:#e57474)"
disabled = false
style = "fg:#dadada"

[cmd_duration]
disabled = true

[docker_context]
disabled=true
symbol = " "

[conda]
disabled=true
symbol = " "

[dart]
disabled=true
symbol = " "

[package]
disabled=true
symbol = " "

[perl]
disabled=true
symbol = " "

[php]
disabled=true
symbol = " "

[ruby]
disabled=true
symbol = " "

[java]
disabled=true
symbol = " "

[lua]
disabled=false
symbol = " "
style = "bold blue"

[nodejs]
disabled=false

[swift]
disabled=true
symbol = "ﯣ "

[julia]
disabled=true
format = "[$symbol$version]($style) "
symbol = "ஃ "
style = "bold green"

[python]
disabled=false
# format = 'via [${symbol}${pyenv_prefix}${version}( $virtualenv)]($style) '
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "
style = "italic bold yellow"

[rust]
disabled=false
format = "on [$symbol$version]($style) "
# style = "bold green"
symbol = " "

[cmake]
disabled = false
format = "via [$symbol($version )]($style)"
style = "bold red"

# add_newline = false


# format = "$directory$git_branch$git_status$memory_usage$character"

# [directory]
# format = "[$path]($style)[  ](bold blue)[$read_only]($read_only_style) "
# truncation_length = 1
# truncate_to_repo =false
# home_symbol = "  "

# [character]
# success_symbol = "[»](green)"
# error_symbol = "[»](red)"
# vicmd_symbol = "[«](green)"

# [git_branch]
# format = "[$symbol$branch ]($style)"
# symbol = " "
# style = "bold #C678DD"
