require "core.settings"
require "core.mappings"
require "core.plugins"
require "core.autocommands"
require "modules.ui.theme"
require "custom.statusline"
require "custom.overrides"
require "custom.abbrev"
